<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" >
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- CSRF Token -->
		  <meta content="e-Procurement Dharma Polimetal" name="description">
 		 <meta content="eproc,Dharma Polimetal,eprocurement" name="keywords">
		<meta name="csrf-token" content="{{ csrf_token() }}">
		{{-- <title>{{ config('app.name', 'eProc Dharma Polimetal') }}</title --}}
		<title>Lockscreen | eProc Dharma Polimetal</title>

		<link rel="icon" type="image/x-icon" href="{{ asset('img/favicon3.png') }}" />
	    <link rel="SHORTCUT ICON" href="{{ asset('img/favicon3.png') }}" />
	    <link rel="icon" href="{{ asset('img/favicon.ico') }}" type="image/ico" />
		   <!-- Scripts -->
		<!--script src="{{ asset('js/app.js') }}" defer></script-->
		<!-- Fonts -->
		<link rel="dns-prefetch" href="//fonts.gstatic.com">
		<link rel="dns-prefetch" href="//cdn.jsdelivr.net">
		<link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
		<!-- Styles -->
		<!--link href="{{ asset('css/app.css') }}" rel="stylesheet"-->
		
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{{ asset('assets/login/vendor/bootstrap/css/bootstrap.min.css') }}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{{ asset('assets/login/fonts/font-awesome-4.7.0/css/font-awesome.min.css') }}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{{ asset('assets/login/fonts/Linearicons-Free-v1.0.0/icon-font.min.css') }}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{{ asset('assets/login/vendor/animate/animate.css') }}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{{ asset('assets/login/vendor/css-hamburgers/hamburgers.min.css') }}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{{ asset('assets/login/vendor/animsition/css/animsition.min.css') }}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{{ asset('assets/login/vendor/select2/select2.min.css') }}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{{ asset('assets/login/vendor/daterangepicker/daterangepicker.css') }}">
		<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{{ asset('assets/login/css/util.css') }}">
		<link rel="stylesheet" type="text/css" href="{{ asset('assets/login/css/main.css') }}">
		<!--===============================================================================================-->
		<link rel="stylesheet" href="{{ asset('assets/login/css/w3.css') }}">
		<link rel="stylesheet" href="{{ asset('assets/login/css/animate.css') }}">
		<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
		<!-- Bootstrap 3.3.6 -->
		<link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
		<!-- Theme style -->
		<link href="{{ asset('css/AdminLTE.css') }}" rel="stylesheet" type="text/css" />
		
		<script src="{{ asset('js/sweet-alert/sweetalert.min.js') }}" type="text/javascript"></script>
		
		<link rel="icon" type="image/x-icon" href="{{ asset('img/favicon3.png') }}" />
		<link rel="SHORTCUT ICON" href="{{ asset('img/favicon.ico') }}" />
		<link rel="icon" href="{{ asset('img/favicon.ico') }}" type="image/ico" />
		<style type="text/css">
		.invalid-feedback{
		display:block !important;
		font-size: 10pt;
		}
		.invalid{
		border-color: red !important;
		border-style: solid !important;
		border-width: 1.7px !important;
		}
		</style>
	</head>
	<body class="lockscreen">
		
		<form action="{{route('unlockScreen')}}" method="POST" onsubmit="myLoader()">
			@csrf
			<!-- Automatic element centering using js -->
			<center>
			<div class="center" >
				<div class="headline text-center" id="time" style="color: #fff;">
					<!-- Time auto generated by js -->
					</div><!-- /.headline -->
					
					
					<!-- User name -->
					<div class="lockscreen-name" style="margin-left: 25px; margin-top: 30px;">{{auth()->user()->nm_user}}</div>
					<!-- START LOCK SCREEN ITEM -->
					<div class="lockscreen-item ">
						<!-- lockscreen image -->
						<div class="lockscreen-image">
							
							<img src="{{asset('img/user.png')}}" alt="user image"/>
						</div>
						<!-- /.lockscreen-image -->
						<input type="hidden" id="id_user" name="id_user" value ="{{auth()->user()->_id}}">
						<input type="hidden" id="username" name="username" value ="{{auth()->user()->username}}">
						<!-- lockscreen credentials (contains the form) -->
						<div class="lockscreen-credentials">
							<div class="input-group ">
								<input type="password" id="password" name="password" required class="form-control" placeholder="password" />
								<div class="input-group-btn">
									<button type="submit" name='login' class="btn btn-flat" ><i class="fa fa-arrow-right text-muted"></i></button>
								</div>
							</div>
							</div><!-- /.lockscreen credentials -->
							</div><!-- /.lockscreen-item -->
							<div class="lockscreen-link">
								<a href="{{ url('/logout') }}" class ="btn btn-flat" >
									<span class='badge bg-green'> Or login as a different user</span>
								</a>
							</div>
							</div><!-- /.center -->
							</center>
						</form>
						<!-- jQuery 2.0.2 -->
						<!--
						<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
						-->
						<script src="{{ asset('jquery-2/jquery.min.js') }}"></script>
						<!--===============================================================================================-->
						<script src="{{ asset('assets/login/vendor/animsition/js/animsition.min.js') }}"></script>
						<!--===============================================================================================-->
						<script src="{{ asset('assets/login/vendor/bootstrap/js/popper.js') }}"></script>
						<script src="{{ asset('assets/login/vendor/bootstrap/js/bootstrap.min.js') }}"></script>
						<!--===============================================================================================-->
						<script src="{{ asset('assets/login/vendor/select2/select2.min.js') }}"></script>
						<!--===============================================================================================-->
						<script src="{{ asset('assets/login/vendor/daterangepicker/moment.min.js') }}"></script>
						<script src="{{ asset('assets/login/vendor/daterangepicker/daterangepicker.js') }}"></script>
						<!--===============================================================================================-->
						<script src="{{ asset('assets/login/vendor/countdowntime/countdowntime.js') }}"></script>
						<!--===============================================================================================-->
						<script src="{{ asset('assets/login/js/main.js') }}"></script>
						
						<script src="{{ asset('js/bootstrap.min.js') }}" type="text/javascript"></script>
						
						<script src="{{ asset('js/jquery-ui-1.10.3.min.js') }}" type="text/javascript"></script>

        <!-- page script -->
        <script type="text/javascript">
            $(function() {
                startTime();
                $(".center").center();
                $(window).resize(function() {
                    $(".center").center();
                });
            });

            /*  */
            function startTime()
            {
                var today = new Date();
                var h = today.getHours();
                var m = today.getMinutes();
                var s = today.getSeconds();

                // add a zero in front of numbers<10
                m = checkTime(m);
                s = checkTime(s);

                //Check for PM and AM
                var day_or_night = (h > 11) ? "PM" : "AM";

                //Convert to 12 hours system
                if (h > 12)
                    h -= 12;

                //Add time to the headline and update every 500 milliseconds
                $('#time').html(h + ":" + m + ":" + s + " " + day_or_night);
                setTimeout(function() {
                    startTime()
                }, 500);
            }

            function checkTime(i)
            {
                if (i < 10)
                {
                    i = "0" + i;
                }
                return i;
            }

            /* CENTER ELEMENTS IN THE SCREEN */
            jQuery.fn.center = function() {
                this.css("position", "absolute");
                this.css("top", Math.max(0, (($(window).height() - $(this).outerHeight()) / 2) +
                        $(window).scrollTop()) - 30 + "px");
                this.css("left", Math.max(0, (($(window).width() - $(this).outerWidth()) / 2) +
                        $(window).scrollLeft()) + "px");
                return this;
            }
        </script>

        <script>
        	$(document).ready(function(){
        	  @if(Session::has('message_fail'))
				Swal.fire(
				  '{{Session::pull('message_fail')}}',
				  '',
				  'error'
				)

               @endif
        	})
            function myLoader(){

                swal({
                    title: 'Gathering your information',
                    text: 'Please wait...',
                    allowOutsideClick: false,
                    onOpen: function () {
                        swal.showLoading()
                    }
                })

            }

        </script>
    </body>
</html>