<?php
    session_start();
    include "log-query.php";
    require "../lib/ip-detect.php";
?>

<!DOCTYPE html>
<html class="lockscreen">
    <head>
        <meta charset="UTF-8">
        <title>eProc Dharma Polimetal</title>
        <link rel="icon" type="image/x-icon" href="../../img/favicon3.png" />
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <!-- bootstrap 3.0.2 -->
        <link href="../../css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <!-- font Awesome -->
        <link href="../../css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <!-- Theme style -->
        <link href="../../css/AdminLTE.css" rel="stylesheet" type="text/css" />
         <!-- Ionicons -->
        <link href="../../css/ionicons.min.css" rel="stylesheet" type="text/css" />

        <!-- sweet alert -->
        <link href="../../css/sweet-alert.css" rel="stylesheet" type="text/css" />
        <script src="../../js/sweet-alert/sweetalert.min.js" type="text/javascript"></script>

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>

    <?php
        if (!empty($_SESSION['nm_user']) &&  !empty($_SESSION['id_user']) && !empty($_SESSION['username']) ){
    ?> 

    <form action="" method="POST">
        <!-- Automatic element centering using js -->
        <center>
        <div class="center" >     
            <div class="headline text-center" id="time" style="color: #fff;">
                <!-- Time auto generated by js -->
            </div><!-- /.headline -->
            
            <?php

                    if (isset($_POST['login'])){

                        //require "../conn/conn.php";
                        //get_connection();
                        $ip    = ip_detect();
                        function anti_injection($data){
						  $conn = get_connection();
                          $filter = mysqli_real_escape_string($conn,stripslashes(strip_tags(htmlspecialchars($data,ENT_QUOTES))));
                          return $filter;
                        }
                            $username = anti_injection($_POST['username']);
                            $pass     = anti_injection(md5($_POST['password']));
                            //$username = $_POST['username'];
                            //$pass     = md5($_POST['password']);

                        // pastikan username dan password adalah berupa huruf atau angka.
                        if (!ctype_alnum($pass)){
                            echo "You don't have access to this site!";
                        }else{
                            /*
                            $query = "SELECT * FROM user u
                                    JOIN vendor v ON u.id_user=v.id_user
                                    JOIN tipe_user t on u.id_tipe_user = t.id_tipe_user WHERE username='$username' AND password='$pass'";
                            */
                            //$model = mysql_query($query);
                            $model = get_vendor_login($username, $pass);
                            //$count = mysql_num_rows($model);
                            $count = mysqli_num_rows($model);
        
                            if ($count > 0){
                                //$log = mysql_fetch_array($model);
                                $log = mysqli_fetch_array($model);
                                //$tgl_sekarang = date("Ymd");
                                //$ip = $_SERVER['REMOTE_ADDR'];
            
                                include "../lib/timeout.php";
                                include "../lib/library.php";
            
                                $_SESSION['id_user']        = $log['id_user'];
                                $_SESSION['username']       = $log['username'];
                                $_SESSION['nm_user']        = $log['nm_user'];
                                $_SESSION['nm_vendor']      = $log['nm_vendor'];
                                $_SESSION['role']           = $log['role'];
                                $_SESSION['nm_tipe_user']   = $log['nm_tipe_user'];
                                // session timeout
                                $_SESSION['login'] = 1;
                                timer();
                                $sid_old = session_id();
                                session_regenerate_id();
                                $sid_new = session_id();
                                
                                //mysql_query("UPDATE user SET id_session='$sid_new' WHERE username='$username' AND id_user='".$_SESSION['id_user']."'");
                                set_login($sid_new, $username, $_SESSION['id_user']);
                                insert_user_log_menu($_SESSION['id_user']  , $ip, 'S', 'in', '');
                                header('location:../home.php?mnu=home');
                
                            }else{
                                /*
                                $query = "SELECT * FROM user u JOIN tipe_user t on u.id_tipe_user = t.id_tipe_user WHERE username='$username' AND password='$pass'";
                                */
                                //$model = mysql_query($query);
                                $model = get_user_login($username, $pass);
                                //$count = mysql_num_rows($model);
                                $count = mysqli_num_rows($model);
        
                                if ($count > 0){
                                    //$log = mysql_fetch_array($model);
                                    $log = mysqli_fetch_array($model);
                                    //$tgl_sekarang = date("Ymd");
                                    //$ip = $_SERVER['REMOTE_ADDR'];
            
                                    include "../lib/timeout.php";
                                    include "../lib/library.php";
            
                                    $_SESSION['id_user']        = $log['id_user'];
                                    $_SESSION['username']       = $log['username'];
                                    $_SESSION['nm_user']        = $log['nm_user'];
                                    $_SESSION['role']           = $log['role'];
                                    $_SESSION['nm_tipe_user']   = $log['nm_tipe_user'];
                                    // session timeout
                                    $_SESSION['login'] = 1;
                                    timer();
                                    $sid_old = session_id();
                                    session_regenerate_id();
                                    $sid_new = session_id();
                                    //mysql_query("UPDATE user SET id_session='$sid_new' WHERE username='$username' AND id_user='".$_SESSION['id_user']."'");
                                    set_login($sid_new, $username, $_SESSION['id_user']);
                                    insert_user_log_menu($_SESSION['id_user']  , $ip, 'S', 'in', '');
                                    header('location:../home.php?mnu=home');
                                }
                                else
                                {

                                    /*
                                    echo
                                    '   
                                    <div class="callout callout-danger alert-dismissable">
                                        <center>
                                        <medium><i class="fa fa-warning"></i> Please give correct password! Or login as different user</medium>
                                        </center>
                                    </div>
                                   
                                    ';
                                    */
                                    insert_user_log_menu('', $ip, 'F', 'in', $username);

                                    echo "
                                        <script>
                                            swal({
                                                title: \"Error!\",
                                                text: \"You typed the wrong password!\",
                                                type: \"error\",
                                                customClass: 'swal-wide',
                                                allowOutsideClick: false
                                            }).then(function() {
                                                swal({
                                                    title: 'Securing',
                                                    text: 'For your secure, we\'ll redirect you to eProc Dharma Polimetal...',
                                                    allowOutsideClick: false,
                                                    timer: 2000,
                                                    onOpen: function () {
                                                        swal.showLoading()
                                                    }
                                                }).then(function () {
                                                },
                                                    // handling the promise rejection
                                                    function (dismiss) {
                                                        if (dismiss === 'timer') {
                                                            window.location.href = '../login.php';
                                                        }
                                                    }
                                                )
                                            });
                                        </script>
                                    ";

                                }// else

                            }//ELSE OF if ($count > 0)
    
                        }//if (!ctype_alnum($username) OR !ctype_alnum($pass))

                    }//if (isset($_POST['login'])){

                ?>

            <!-- User name -->
            <div class="lockscreen-name" style="margin-left: 25px; margin-top: 30px;"><?php  echo $_SESSION['nm_user'];  ?></div>

            <!-- START LOCK SCREEN ITEM -->
            <div class="lockscreen-item ">
                <!-- lockscreen image -->
                <div class="lockscreen-image">
    
                    <img src="../../img/user.png" alt="user image"/>

                </div>
                <!-- /.lockscreen-image -->

                <input type="hidden" id="id_user" name="id_user" value ="<?php echo $_SESSION['id_user']; ?>">
                <input type="hidden" id="username" name="username" value ="<?php echo $_SESSION['username']; ?>">

                <!-- lockscreen credentials (contains the form) -->
                <div class="lockscreen-credentials">   

                    <div class="input-group ">
                        <input type="password" id="password" name="password" class="form-control" placeholder="password" />
                        <div class="input-group-btn">
                            <button type="submit" name='login' class="btn btn-flat" onclick="myLoader()"><i class="fa fa-arrow-right text-muted"></i></button>
                        </div>
                    </div>
                </div><!-- /.lockscreen credentials -->

            </div><!-- /.lockscreen-item -->

            <div class="lockscreen-link">
                <a href="../login.php" class ="btn btn-flat" >
                    <span class='badge bg-green'> Or login as a different user</span>
                </a>
            </div>           
        </div><!-- /.center -->
        </center>
    </form> 

    <?php

        } else {

            echo "
                 <script>
                     swal({
                         title: \"Error!\",
                         text: \"You typed the wrong password!\",
                         type: \"error\",
                         customClass: 'swal-wide',
                         allowOutsideClick: false
                     }).then(function() {
                         swal({
                             title: 'Securing',
                             text: 'For your secure, we\'ll redirect you to eProc Dharma Polimetal...',
                             allowOutsideClick: false,
                             timer: 2000,
                             onOpen: function () {
                                 swal.showLoading()
                             }
                         }).then(function () {
                         },
                             // handling the promise rejection
                             function (dismiss) {
                                 if (dismiss === 'timer') {
                                     window.location.href = '../login.php';
                                 }
                             }
                         )
                     });
                 </script>
            ";
            //header('location:');
        }
    ?>

        <!-- jQuery 2.0.2 -->
        <!--
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
        -->
        <script src="../../jquery-2/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="../../js/bootstrap.min.js" type="text/javascript"></script>

        <!-- page script -->
        <script type="text/javascript">
            $(function() {
                startTime();
                $(".center").center();
                $(window).resize(function() {
                    $(".center").center();
                });
            });

            /*  */
            function startTime()
            {
                var today = new Date();
                var h = today.getHours();
                var m = today.getMinutes();
                var s = today.getSeconds();

                // add a zero in front of numbers<10
                m = checkTime(m);
                s = checkTime(s);

                //Check for PM and AM
                var day_or_night = (h > 11) ? "PM" : "AM";

                //Convert to 12 hours system
                if (h > 12)
                    h -= 12;

                //Add time to the headline and update every 500 milliseconds
                $('#time').html(h + ":" + m + ":" + s + " " + day_or_night);
                setTimeout(function() {
                    startTime()
                }, 500);
            }

            function checkTime(i)
            {
                if (i < 10)
                {
                    i = "0" + i;
                }
                return i;
            }

            /* CENTER ELEMENTS IN THE SCREEN */
            jQuery.fn.center = function() {
                this.css("position", "absolute");
                this.css("top", Math.max(0, (($(window).height() - $(this).outerHeight()) / 2) +
                        $(window).scrollTop()) - 30 + "px");
                this.css("left", Math.max(0, (($(window).width() - $(this).outerWidth()) / 2) +
                        $(window).scrollLeft()) + "px");
                return this;
            }
        </script>

        <script>

            function myLoader(){

                swal({
                    title: 'Gathering your information',
                    text: 'Please wait...',
                    allowOutsideClick: false,
                    onOpen: function () {
                        swal.showLoading()
                    }
                })

            }

        </script>
    </body>
</html>